(cl:in-package owd_msgs-msg)
(cl:export '(POSITIONS-VAL
          POSITIONS
          TOTAL_TORQUE-VAL
          TOTAL_TORQUE
          DYNAMIC_TORQUE-VAL
          DYNAMIC_TORQUE
          TRAJECTORY_TORQUE-VAL
          TRAJECTORY_TORQUE
          SIM_TORQUE-VAL
          SIM_TORQUE
          JOINT_OFFSETS-VAL
          JOINT_OFFSETS
          GAINS-VAL
          GAINS
          ELBOW_VELOCITY-VAL
          ELBOW_VELOCITY
          ENDPOINT_VELOCITY-VAL
          ENDPOINT_VELOCITY
          BARRETT_ENDPOINT_VELOCITY-VAL
          BARRETT_ENDPOINT_VELOCITY
))