barrett_hand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20.0 
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: finger_1_med_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: finger_2_med_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: finger_3_med_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: finger_1_prox_joint
    pid: {p: 1.0, i: 0.0, d: 0.0}



