/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/ApplyEEForceTorque.srv */
#ifndef OWD_MSGS_SERVICE_APPLYEEFORCETORQUE_H
#define OWD_MSGS_SERVICE_APPLYEEFORCETORQUE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct ApplyEEForceTorqueRequest_ {
  typedef ApplyEEForceTorqueRequest_<ContainerAllocator> Type;

  ApplyEEForceTorqueRequest_()
  : force_x(0.0)
  , force_y(0.0)
  , force_z(0.0)
  , torque_x(0.0)
  , torque_y(0.0)
  , torque_z(0.0)
  , vibrate_hand_x(0.0)
  , vibrate_hand_y(0.0)
  , vibrate_hand_z(0.0)
  , vibrate_amplitude_m(0.0)
  , vibrate_frequency_hz(0.0)
  , rotational_compliance(false)
  {
  }

  ApplyEEForceTorqueRequest_(const ContainerAllocator& _alloc)
  : force_x(0.0)
  , force_y(0.0)
  , force_z(0.0)
  , torque_x(0.0)
  , torque_y(0.0)
  , torque_z(0.0)
  , vibrate_hand_x(0.0)
  , vibrate_hand_y(0.0)
  , vibrate_hand_z(0.0)
  , vibrate_amplitude_m(0.0)
  , vibrate_frequency_hz(0.0)
  , rotational_compliance(false)
  {
  }

  typedef double _force_x_type;
  double force_x;

  typedef double _force_y_type;
  double force_y;

  typedef double _force_z_type;
  double force_z;

  typedef double _torque_x_type;
  double torque_x;

  typedef double _torque_y_type;
  double torque_y;

  typedef double _torque_z_type;
  double torque_z;

  typedef double _vibrate_hand_x_type;
  double vibrate_hand_x;

  typedef double _vibrate_hand_y_type;
  double vibrate_hand_y;

  typedef double _vibrate_hand_z_type;
  double vibrate_hand_z;

  typedef double _vibrate_amplitude_m_type;
  double vibrate_amplitude_m;

  typedef double _vibrate_frequency_hz_type;
  double vibrate_frequency_hz;

  typedef uint8_t _rotational_compliance_type;
  uint8_t rotational_compliance;


  typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ApplyEEForceTorqueRequest
typedef  ::owd_msgs::ApplyEEForceTorqueRequest_<std::allocator<void> > ApplyEEForceTorqueRequest;

typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueRequest> ApplyEEForceTorqueRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueRequest const> ApplyEEForceTorqueRequestConstPtr;



template <class ContainerAllocator>
struct ApplyEEForceTorqueResponse_ {
  typedef ApplyEEForceTorqueResponse_<ContainerAllocator> Type;

  ApplyEEForceTorqueResponse_()
  : ok(false)
  , reason()
  , id()
  {
  }

  ApplyEEForceTorqueResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  , id(_alloc)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  id;


  typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ApplyEEForceTorqueResponse
typedef  ::owd_msgs::ApplyEEForceTorqueResponse_<std::allocator<void> > ApplyEEForceTorqueResponse;

typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueResponse> ApplyEEForceTorqueResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::ApplyEEForceTorqueResponse const> ApplyEEForceTorqueResponseConstPtr;


struct ApplyEEForceTorque
{

typedef ApplyEEForceTorqueRequest Request;
typedef ApplyEEForceTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ApplyEEForceTorque
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d0058643910880c910961a823742fb0e";
  }

  static const char* value(const  ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd0058643910880c9ULL;
  static const uint64_t static_value2 = 0x10961a823742fb0eULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ApplyEEForceTorqueRequest";
  }

  static const char* value(const  ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
float64 force_x\n\
float64 force_y\n\
float64 force_z\n\
float64 torque_x\n\
float64 torque_y\n\
float64 torque_z\n\
float64 vibrate_hand_x\n\
float64 vibrate_hand_y\n\
float64 vibrate_hand_z\n\
float64 vibrate_amplitude_m\n\
float64 vibrate_frequency_hz\n\
bool rotational_compliance\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "222302c2ef507be891c9d6982f07467f";
  }

  static const char* value(const  ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x222302c2ef507be8ULL;
  static const uint64_t static_value2 = 0x91c9d6982f07467fULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ApplyEEForceTorqueResponse";
  }

  static const char* value(const  ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
string id\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.force_x);
    stream.next(m.force_y);
    stream.next(m.force_z);
    stream.next(m.torque_x);
    stream.next(m.torque_y);
    stream.next(m.torque_z);
    stream.next(m.vibrate_hand_x);
    stream.next(m.vibrate_hand_y);
    stream.next(m.vibrate_hand_z);
    stream.next(m.vibrate_amplitude_m);
    stream.next(m.vibrate_frequency_hz);
    stream.next(m.rotational_compliance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ApplyEEForceTorqueRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
    stream.next(m.id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ApplyEEForceTorqueResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::ApplyEEForceTorque> {
  static const char* value() 
  {
    return "ade9ee218c22318a69c014df7b555430";
  }

  static const char* value(const owd_msgs::ApplyEEForceTorque&) { return value(); } 
};

template<>
struct DataType<owd_msgs::ApplyEEForceTorque> {
  static const char* value() 
  {
    return "owd_msgs/ApplyEEForceTorque";
  }

  static const char* value(const owd_msgs::ApplyEEForceTorque&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ade9ee218c22318a69c014df7b555430";
  }

  static const char* value(const owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ApplyEEForceTorque";
  }

  static const char* value(const owd_msgs::ApplyEEForceTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ade9ee218c22318a69c014df7b555430";
  }

  static const char* value(const owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ApplyEEForceTorque";
  }

  static const char* value(const owd_msgs::ApplyEEForceTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_APPLYEEFORCETORQUE_H

