/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/DeleteTrajectory.srv */
#ifndef OWD_MSGS_SERVICE_DELETETRAJECTORY_H
#define OWD_MSGS_SERVICE_DELETETRAJECTORY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct DeleteTrajectoryRequest_ {
  typedef DeleteTrajectoryRequest_<ContainerAllocator> Type;

  DeleteTrajectoryRequest_()
  : ids()
  {
  }

  DeleteTrajectoryRequest_(const ContainerAllocator& _alloc)
  : ids(_alloc)
  {
  }

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _ids_type;
  std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  ids;


  typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DeleteTrajectoryRequest
typedef  ::owd_msgs::DeleteTrajectoryRequest_<std::allocator<void> > DeleteTrajectoryRequest;

typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryRequest> DeleteTrajectoryRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryRequest const> DeleteTrajectoryRequestConstPtr;



template <class ContainerAllocator>
struct DeleteTrajectoryResponse_ {
  typedef DeleteTrajectoryResponse_<ContainerAllocator> Type;

  DeleteTrajectoryResponse_()
  : ok(false)
  , reason()
  {
  }

  DeleteTrajectoryResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;


  typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DeleteTrajectoryResponse
typedef  ::owd_msgs::DeleteTrajectoryResponse_<std::allocator<void> > DeleteTrajectoryResponse;

typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryResponse> DeleteTrajectoryResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::DeleteTrajectoryResponse const> DeleteTrajectoryResponseConstPtr;


struct DeleteTrajectory
{

typedef DeleteTrajectoryRequest Request;
typedef DeleteTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct DeleteTrajectory
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "31314a1125a2ca69ddc92cdc117c989c";
  }

  static const char* value(const  ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x31314a1125a2ca69ULL;
  static const uint64_t static_value2 = 0xddc92cdc117c989cULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/DeleteTrajectoryRequest";
  }

  static const char* value(const  ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string[] ids\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const  ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4679398f882e7cbdULL;
  static const uint64_t static_value2 = 0xea165980d3ec2888ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/DeleteTrajectoryResponse";
  }

  static const char* value(const  ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ids);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DeleteTrajectoryRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DeleteTrajectoryResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::DeleteTrajectory> {
  static const char* value() 
  {
    return "ae5f0ecb1e1d1f21c66a723bc36404cb";
  }

  static const char* value(const owd_msgs::DeleteTrajectory&) { return value(); } 
};

template<>
struct DataType<owd_msgs::DeleteTrajectory> {
  static const char* value() 
  {
    return "owd_msgs/DeleteTrajectory";
  }

  static const char* value(const owd_msgs::DeleteTrajectory&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ae5f0ecb1e1d1f21c66a723bc36404cb";
  }

  static const char* value(const owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/DeleteTrajectory";
  }

  static const char* value(const owd_msgs::DeleteTrajectoryRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ae5f0ecb1e1d1f21c66a723bc36404cb";
  }

  static const char* value(const owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/DeleteTrajectory";
  }

  static const char* value(const owd_msgs::DeleteTrajectoryResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_DELETETRAJECTORY_H

