/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/GetStiffness.srv */
#ifndef OWD_MSGS_SERVICE_GETSTIFFNESS_H
#define OWD_MSGS_SERVICE_GETSTIFFNESS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct GetStiffnessRequest_ {
  typedef GetStiffnessRequest_<ContainerAllocator> Type;

  GetStiffnessRequest_()
  {
  }

  GetStiffnessRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetStiffnessRequest
typedef  ::owd_msgs::GetStiffnessRequest_<std::allocator<void> > GetStiffnessRequest;

typedef boost::shared_ptr< ::owd_msgs::GetStiffnessRequest> GetStiffnessRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::GetStiffnessRequest const> GetStiffnessRequestConstPtr;



template <class ContainerAllocator>
struct GetStiffnessResponse_ {
  typedef GetStiffnessResponse_<ContainerAllocator> Type;

  GetStiffnessResponse_()
  : ok(false)
  , reason()
  , stiffness(0.0)
  {
  }

  GetStiffnessResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  , stiffness(0.0)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;

  typedef float _stiffness_type;
  float stiffness;


  typedef boost::shared_ptr< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetStiffnessResponse
typedef  ::owd_msgs::GetStiffnessResponse_<std::allocator<void> > GetStiffnessResponse;

typedef boost::shared_ptr< ::owd_msgs::GetStiffnessResponse> GetStiffnessResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::GetStiffnessResponse const> GetStiffnessResponseConstPtr;


struct GetStiffness
{

typedef GetStiffnessRequest Request;
typedef GetStiffnessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetStiffness
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStiffnessRequest";
  }

  static const char* value(const  ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "369c1f1022dd58bd3c86927727e1ddb4";
  }

  static const char* value(const  ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x369c1f1022dd58bdULL;
  static const uint64_t static_value2 = 0x3c86927727e1ddb4ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStiffnessResponse";
  }

  static const char* value(const  ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
\n\
float32 stiffness\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::GetStiffnessRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetStiffnessRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::GetStiffnessResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
    stream.next(m.stiffness);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetStiffnessResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::GetStiffness> {
  static const char* value() 
  {
    return "369c1f1022dd58bd3c86927727e1ddb4";
  }

  static const char* value(const owd_msgs::GetStiffness&) { return value(); } 
};

template<>
struct DataType<owd_msgs::GetStiffness> {
  static const char* value() 
  {
    return "owd_msgs/GetStiffness";
  }

  static const char* value(const owd_msgs::GetStiffness&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::GetStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "369c1f1022dd58bd3c86927727e1ddb4";
  }

  static const char* value(const owd_msgs::GetStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::GetStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStiffness";
  }

  static const char* value(const owd_msgs::GetStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::GetStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "369c1f1022dd58bd3c86927727e1ddb4";
  }

  static const char* value(const owd_msgs::GetStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::GetStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStiffness";
  }

  static const char* value(const owd_msgs::GetStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_GETSTIFFNESS_H

