/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/GetStallSensitivity.srv */
#ifndef OWD_MSGS_SERVICE_GETSTALLSENSITIVITY_H
#define OWD_MSGS_SERVICE_GETSTALLSENSITIVITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct GetStallSensitivityRequest_ {
  typedef GetStallSensitivityRequest_<ContainerAllocator> Type;

  GetStallSensitivityRequest_()
  {
  }

  GetStallSensitivityRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetStallSensitivityRequest
typedef  ::owd_msgs::GetStallSensitivityRequest_<std::allocator<void> > GetStallSensitivityRequest;

typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityRequest> GetStallSensitivityRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityRequest const> GetStallSensitivityRequestConstPtr;



template <class ContainerAllocator>
struct GetStallSensitivityResponse_ {
  typedef GetStallSensitivityResponse_<ContainerAllocator> Type;

  GetStallSensitivityResponse_()
  : level(0.0)
  {
  }

  GetStallSensitivityResponse_(const ContainerAllocator& _alloc)
  : level(0.0)
  {
  }

  typedef float _level_type;
  float level;


  typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetStallSensitivityResponse
typedef  ::owd_msgs::GetStallSensitivityResponse_<std::allocator<void> > GetStallSensitivityResponse;

typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityResponse> GetStallSensitivityResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::GetStallSensitivityResponse const> GetStallSensitivityResponseConstPtr;


struct GetStallSensitivity
{

typedef GetStallSensitivityRequest Request;
typedef GetStallSensitivityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetStallSensitivity
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStallSensitivityRequest";
  }

  static const char* value(const  ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "480b3e33acc20b8f29c6011b379fbc8b";
  }

  static const char* value(const  ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x480b3e33acc20b8fULL;
  static const uint64_t static_value2 = 0x29c6011b379fbc8bULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStallSensitivityResponse";
  }

  static const char* value(const  ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 level\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetStallSensitivityRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.level);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetStallSensitivityResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::GetStallSensitivity> {
  static const char* value() 
  {
    return "480b3e33acc20b8f29c6011b379fbc8b";
  }

  static const char* value(const owd_msgs::GetStallSensitivity&) { return value(); } 
};

template<>
struct DataType<owd_msgs::GetStallSensitivity> {
  static const char* value() 
  {
    return "owd_msgs/GetStallSensitivity";
  }

  static const char* value(const owd_msgs::GetStallSensitivity&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "480b3e33acc20b8f29c6011b379fbc8b";
  }

  static const char* value(const owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStallSensitivity";
  }

  static const char* value(const owd_msgs::GetStallSensitivityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "480b3e33acc20b8f29c6011b379fbc8b";
  }

  static const char* value(const owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/GetStallSensitivity";
  }

  static const char* value(const owd_msgs::GetStallSensitivityResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_GETSTALLSENSITIVITY_H

