/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/ResetHand.srv */
#ifndef OWD_MSGS_SERVICE_RESETHAND_H
#define OWD_MSGS_SERVICE_RESETHAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct ResetHandRequest_ {
  typedef ResetHandRequest_<ContainerAllocator> Type;

  ResetHandRequest_()
  {
  }

  ResetHandRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::owd_msgs::ResetHandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::ResetHandRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ResetHandRequest
typedef  ::owd_msgs::ResetHandRequest_<std::allocator<void> > ResetHandRequest;

typedef boost::shared_ptr< ::owd_msgs::ResetHandRequest> ResetHandRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::ResetHandRequest const> ResetHandRequestConstPtr;



template <class ContainerAllocator>
struct ResetHandResponse_ {
  typedef ResetHandResponse_<ContainerAllocator> Type;

  ResetHandResponse_()
  : ok(false)
  , reason()
  {
  }

  ResetHandResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;


  typedef boost::shared_ptr< ::owd_msgs::ResetHandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::ResetHandResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ResetHandResponse
typedef  ::owd_msgs::ResetHandResponse_<std::allocator<void> > ResetHandResponse;

typedef boost::shared_ptr< ::owd_msgs::ResetHandResponse> ResetHandResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::ResetHandResponse const> ResetHandResponseConstPtr;


struct ResetHand
{

typedef ResetHandRequest Request;
typedef ResetHandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ResetHand
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ResetHandRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ResetHandRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::ResetHandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::owd_msgs::ResetHandRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::ResetHandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ResetHandRequest";
  }

  static const char* value(const  ::owd_msgs::ResetHandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::ResetHandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::owd_msgs::ResetHandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::ResetHandRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ResetHandResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ResetHandResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::ResetHandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const  ::owd_msgs::ResetHandResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4679398f882e7cbdULL;
  static const uint64_t static_value2 = 0xea165980d3ec2888ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::ResetHandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ResetHandResponse";
  }

  static const char* value(const  ::owd_msgs::ResetHandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::ResetHandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::ResetHandResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::ResetHandRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ResetHandRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::ResetHandResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ResetHandResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::ResetHand> {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const owd_msgs::ResetHand&) { return value(); } 
};

template<>
struct DataType<owd_msgs::ResetHand> {
  static const char* value() 
  {
    return "owd_msgs/ResetHand";
  }

  static const char* value(const owd_msgs::ResetHand&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::ResetHandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const owd_msgs::ResetHandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::ResetHandRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ResetHand";
  }

  static const char* value(const owd_msgs::ResetHandRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::ResetHandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const owd_msgs::ResetHandResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::ResetHandResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ResetHand";
  }

  static const char* value(const owd_msgs::ResetHandResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_RESETHAND_H

