/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/SetHandTorque.srv */
#ifndef OWD_MSGS_SERVICE_SETHANDTORQUE_H
#define OWD_MSGS_SERVICE_SETHANDTORQUE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct SetHandTorqueRequest_ {
  typedef SetHandTorqueRequest_<ContainerAllocator> Type;

  SetHandTorqueRequest_()
  : initial(0)
  , sustained(0)
  {
  }

  SetHandTorqueRequest_(const ContainerAllocator& _alloc)
  : initial(0)
  , sustained(0)
  {
  }

  typedef int32_t _initial_type;
  int32_t initial;

  typedef int32_t _sustained_type;
  int32_t sustained;


  typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetHandTorqueRequest
typedef  ::owd_msgs::SetHandTorqueRequest_<std::allocator<void> > SetHandTorqueRequest;

typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueRequest> SetHandTorqueRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueRequest const> SetHandTorqueRequestConstPtr;



template <class ContainerAllocator>
struct SetHandTorqueResponse_ {
  typedef SetHandTorqueResponse_<ContainerAllocator> Type;

  SetHandTorqueResponse_()
  : ok(false)
  , reason()
  {
  }

  SetHandTorqueResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;


  typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetHandTorqueResponse
typedef  ::owd_msgs::SetHandTorqueResponse_<std::allocator<void> > SetHandTorqueResponse;

typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueResponse> SetHandTorqueResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::SetHandTorqueResponse const> SetHandTorqueResponseConstPtr;


struct SetHandTorque
{

typedef SetHandTorqueRequest Request;
typedef SetHandTorqueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetHandTorque
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "161f9c0cf0aa41f1f00bf291ccdff7d0";
  }

  static const char* value(const  ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x161f9c0cf0aa41f1ULL;
  static const uint64_t static_value2 = 0xf00bf291ccdff7d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetHandTorqueRequest";
  }

  static const char* value(const  ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 initial\n\
int32 sustained\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const  ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4679398f882e7cbdULL;
  static const uint64_t static_value2 = 0xea165980d3ec2888ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetHandTorqueResponse";
  }

  static const char* value(const  ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::SetHandTorqueRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.initial);
    stream.next(m.sustained);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetHandTorqueRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::SetHandTorqueResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetHandTorqueResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::SetHandTorque> {
  static const char* value() 
  {
    return "25f05b3c85731e4fc054b0dcb3c9b8a3";
  }

  static const char* value(const owd_msgs::SetHandTorque&) { return value(); } 
};

template<>
struct DataType<owd_msgs::SetHandTorque> {
  static const char* value() 
  {
    return "owd_msgs/SetHandTorque";
  }

  static const char* value(const owd_msgs::SetHandTorque&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "25f05b3c85731e4fc054b0dcb3c9b8a3";
  }

  static const char* value(const owd_msgs::SetHandTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::SetHandTorqueRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetHandTorque";
  }

  static const char* value(const owd_msgs::SetHandTorqueRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "25f05b3c85731e4fc054b0dcb3c9b8a3";
  }

  static const char* value(const owd_msgs::SetHandTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::SetHandTorqueResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetHandTorque";
  }

  static const char* value(const owd_msgs::SetHandTorqueResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_SETHANDTORQUE_H

