/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/SetJointOffsets.srv */
#ifndef OWD_MSGS_SERVICE_SETJOINTOFFSETS_H
#define OWD_MSGS_SERVICE_SETJOINTOFFSETS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct SetJointOffsetsRequest_ {
  typedef SetJointOffsetsRequest_<ContainerAllocator> Type;

  SetJointOffsetsRequest_()
  : offset()
  {
  }

  SetJointOffsetsRequest_(const ContainerAllocator& _alloc)
  : offset(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _offset_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  offset;


  typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetJointOffsetsRequest
typedef  ::owd_msgs::SetJointOffsetsRequest_<std::allocator<void> > SetJointOffsetsRequest;

typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsRequest> SetJointOffsetsRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsRequest const> SetJointOffsetsRequestConstPtr;



template <class ContainerAllocator>
struct SetJointOffsetsResponse_ {
  typedef SetJointOffsetsResponse_<ContainerAllocator> Type;

  SetJointOffsetsResponse_()
  : ok(false)
  , reason()
  {
  }

  SetJointOffsetsResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;


  typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetJointOffsetsResponse
typedef  ::owd_msgs::SetJointOffsetsResponse_<std::allocator<void> > SetJointOffsetsResponse;

typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsResponse> SetJointOffsetsResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::SetJointOffsetsResponse const> SetJointOffsetsResponseConstPtr;


struct SetJointOffsets
{

typedef SetJointOffsetsRequest Request;
typedef SetJointOffsetsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetJointOffsets
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "64d8bbc9ac6a377e0857cd689c98857c";
  }

  static const char* value(const  ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x64d8bbc9ac6a377eULL;
  static const uint64_t static_value2 = 0x0857cd689c98857cULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointOffsetsRequest";
  }

  static const char* value(const  ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] offset\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const  ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4679398f882e7cbdULL;
  static const uint64_t static_value2 = 0xea165980d3ec2888ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointOffsetsResponse";
  }

  static const char* value(const  ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.offset);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetJointOffsetsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetJointOffsetsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::SetJointOffsets> {
  static const char* value() 
  {
    return "7a8655e3c68fc4de24d05c081bb29ced";
  }

  static const char* value(const owd_msgs::SetJointOffsets&) { return value(); } 
};

template<>
struct DataType<owd_msgs::SetJointOffsets> {
  static const char* value() 
  {
    return "owd_msgs/SetJointOffsets";
  }

  static const char* value(const owd_msgs::SetJointOffsets&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a8655e3c68fc4de24d05c081bb29ced";
  }

  static const char* value(const owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointOffsets";
  }

  static const char* value(const owd_msgs::SetJointOffsetsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7a8655e3c68fc4de24d05c081bb29ced";
  }

  static const char* value(const owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointOffsets";
  }

  static const char* value(const owd_msgs::SetJointOffsetsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_SETJOINTOFFSETS_H

