/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/SetJointStiffness.srv */
#ifndef OWD_MSGS_SERVICE_SETJOINTSTIFFNESS_H
#define OWD_MSGS_SERVICE_SETJOINTSTIFFNESS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct SetJointStiffnessRequest_ {
  typedef SetJointStiffnessRequest_<ContainerAllocator> Type;

  SetJointStiffnessRequest_()
  : stiffness()
  {
  }

  SetJointStiffnessRequest_(const ContainerAllocator& _alloc)
  : stiffness(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _stiffness_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  stiffness;


  typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetJointStiffnessRequest
typedef  ::owd_msgs::SetJointStiffnessRequest_<std::allocator<void> > SetJointStiffnessRequest;

typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessRequest> SetJointStiffnessRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessRequest const> SetJointStiffnessRequestConstPtr;



template <class ContainerAllocator>
struct SetJointStiffnessResponse_ {
  typedef SetJointStiffnessResponse_<ContainerAllocator> Type;

  SetJointStiffnessResponse_()
  : ok(false)
  , reason()
  {
  }

  SetJointStiffnessResponse_(const ContainerAllocator& _alloc)
  : ok(false)
  , reason(_alloc)
  {
  }

  typedef uint8_t _ok_type;
  uint8_t ok;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  reason;


  typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetJointStiffnessResponse
typedef  ::owd_msgs::SetJointStiffnessResponse_<std::allocator<void> > SetJointStiffnessResponse;

typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessResponse> SetJointStiffnessResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::SetJointStiffnessResponse const> SetJointStiffnessResponseConstPtr;


struct SetJointStiffness
{

typedef SetJointStiffnessRequest Request;
typedef SetJointStiffnessResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetJointStiffness
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3e07126e33eda8ee3f9b2b92a99f9528";
  }

  static const char* value(const  ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3e07126e33eda8eeULL;
  static const uint64_t static_value2 = 0x3f9b2b92a99f9528ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointStiffnessRequest";
  }

  static const char* value(const  ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] stiffness\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4679398f882e7cbdea165980d3ec2888";
  }

  static const char* value(const  ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4679398f882e7cbdULL;
  static const uint64_t static_value2 = 0xea165980d3ec2888ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointStiffnessResponse";
  }

  static const char* value(const  ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool ok\n\
string reason\n\
\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stiffness);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetJointStiffnessRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ok);
    stream.next(m.reason);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetJointStiffnessResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::SetJointStiffness> {
  static const char* value() 
  {
    return "e192d1f69eccc586e7f2b6325b1ee3d6";
  }

  static const char* value(const owd_msgs::SetJointStiffness&) { return value(); } 
};

template<>
struct DataType<owd_msgs::SetJointStiffness> {
  static const char* value() 
  {
    return "owd_msgs/SetJointStiffness";
  }

  static const char* value(const owd_msgs::SetJointStiffness&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e192d1f69eccc586e7f2b6325b1ee3d6";
  }

  static const char* value(const owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointStiffness";
  }

  static const char* value(const owd_msgs::SetJointStiffnessRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e192d1f69eccc586e7f2b6325b1ee3d6";
  }

  static const char* value(const owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/SetJointStiffness";
  }

  static const char* value(const owd_msgs::SetJointStiffnessResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_SETJOINTSTIFFNESS_H

