/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/srv/StopForce.srv */
#ifndef OWD_MSGS_SERVICE_STOPFORCE_H
#define OWD_MSGS_SERVICE_STOPFORCE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace owd_msgs
{
template <class ContainerAllocator>
struct StopForceRequest_ {
  typedef StopForceRequest_<ContainerAllocator> Type;

  StopForceRequest_()
  {
  }

  StopForceRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::owd_msgs::StopForceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::StopForceRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopForceRequest
typedef  ::owd_msgs::StopForceRequest_<std::allocator<void> > StopForceRequest;

typedef boost::shared_ptr< ::owd_msgs::StopForceRequest> StopForceRequestPtr;
typedef boost::shared_ptr< ::owd_msgs::StopForceRequest const> StopForceRequestConstPtr;



template <class ContainerAllocator>
struct StopForceResponse_ {
  typedef StopForceResponse_<ContainerAllocator> Type;

  StopForceResponse_()
  {
  }

  StopForceResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::owd_msgs::StopForceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::StopForceResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct StopForceResponse
typedef  ::owd_msgs::StopForceResponse_<std::allocator<void> > StopForceResponse;

typedef boost::shared_ptr< ::owd_msgs::StopForceResponse> StopForceResponsePtr;
typedef boost::shared_ptr< ::owd_msgs::StopForceResponse const> StopForceResponseConstPtr;


struct StopForce
{

typedef StopForceRequest Request;
typedef StopForceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct StopForce
} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::StopForceRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::StopForceRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::StopForceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::owd_msgs::StopForceRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::StopForceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/StopForceRequest";
  }

  static const char* value(const  ::owd_msgs::StopForceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::StopForceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::owd_msgs::StopForceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::StopForceRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::StopForceResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::StopForceResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::StopForceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::owd_msgs::StopForceResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::StopForceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/StopForceResponse";
  }

  static const char* value(const  ::owd_msgs::StopForceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::StopForceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::StopForceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::owd_msgs::StopForceResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::StopForceRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopForceRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::StopForceResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct StopForceResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<owd_msgs::StopForce> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const owd_msgs::StopForce&) { return value(); } 
};

template<>
struct DataType<owd_msgs::StopForce> {
  static const char* value() 
  {
    return "owd_msgs/StopForce";
  }

  static const char* value(const owd_msgs::StopForce&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::StopForceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const owd_msgs::StopForceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::StopForceRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/StopForce";
  }

  static const char* value(const owd_msgs::StopForceRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<owd_msgs::StopForceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const owd_msgs::StopForceResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<owd_msgs::StopForceResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/StopForce";
  }

  static const char* value(const owd_msgs::StopForceResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MSGS_SERVICE_STOPFORCE_H

