/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/msg/ForceState.msg */
#ifndef OWD_MSGS_MESSAGE_FORCESTATE_H
#define OWD_MSGS_MESSAGE_FORCESTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Wrench.h"

namespace owd_msgs
{
template <class ContainerAllocator>
struct ForceState_ {
  typedef ForceState_<ContainerAllocator> Type;

  ForceState_()
  : header()
  , wrench()
  , saturated_axes(0)
  {
  }

  ForceState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , wrench(_alloc)
  , saturated_axes(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Wrench_<ContainerAllocator>  _wrench_type;
   ::geometry_msgs::Wrench_<ContainerAllocator>  wrench;

  typedef uint8_t _saturated_axes_type;
  uint8_t saturated_axes;


  typedef boost::shared_ptr< ::owd_msgs::ForceState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::ForceState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ForceState
typedef  ::owd_msgs::ForceState_<std::allocator<void> > ForceState;

typedef boost::shared_ptr< ::owd_msgs::ForceState> ForceStatePtr;
typedef boost::shared_ptr< ::owd_msgs::ForceState const> ForceStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::owd_msgs::ForceState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::owd_msgs::ForceState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ForceState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ForceState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::ForceState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f1410afad95483f36c6e47a83ba05017";
  }

  static const char* value(const  ::owd_msgs::ForceState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf1410afad95483f3ULL;
  static const uint64_t static_value2 = 0x6c6e47a83ba05017ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::ForceState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ForceState";
  }

  static const char* value(const  ::owd_msgs::ForceState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::ForceState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Message to contain the state of the force torque data\n\
Header header\n\
geometry_msgs/Wrench wrench\n\
uint8 saturated_axes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Wrench\n\
# This represents force in free space, separated into\n\
# its linear and angular parts.\n\
Vector3  force\n\
Vector3  torque\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::owd_msgs::ForceState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::owd_msgs::ForceState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::owd_msgs::ForceState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::ForceState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.wrench);
    stream.next(m.saturated_axes);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ForceState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::owd_msgs::ForceState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::owd_msgs::ForceState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "wrench: ";
s << std::endl;
    Printer< ::geometry_msgs::Wrench_<ContainerAllocator> >::stream(s, indent + "  ", v.wrench);
    s << indent << "saturated_axes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.saturated_axes);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OWD_MSGS_MESSAGE_FORCESTATE_H

