/* Auto-generated by genmsg_cpp for file /home/kuri/catkin_ws/src/owd_msgs/msg/ForceRead.msg */
#ifndef OWD_MSGS_MESSAGE_FORCEREAD_H
#define OWD_MSGS_MESSAGE_FORCEREAD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace owd_msgs
{
template <class ContainerAllocator>
struct ForceRead_ {
  typedef ForceRead_<ContainerAllocator> Type;

  ForceRead_()
  : force()
  {
  }

  ForceRead_(const ContainerAllocator& _alloc)
  : force(_alloc)
  {
  }

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _force_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  force;


  typedef boost::shared_ptr< ::owd_msgs::ForceRead_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd_msgs::ForceRead_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ForceRead
typedef  ::owd_msgs::ForceRead_<std::allocator<void> > ForceRead;

typedef boost::shared_ptr< ::owd_msgs::ForceRead> ForceReadPtr;
typedef boost::shared_ptr< ::owd_msgs::ForceRead const> ForceReadConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::owd_msgs::ForceRead_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::owd_msgs::ForceRead_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace owd_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ForceRead_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::owd_msgs::ForceRead_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::owd_msgs::ForceRead_<ContainerAllocator> > {
  static const char* value() 
  {
    return "23399487a2048efabaa375690609f3b9";
  }

  static const char* value(const  ::owd_msgs::ForceRead_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x23399487a2048efaULL;
  static const uint64_t static_value2 = 0xbaa375690609f3b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd_msgs::ForceRead_<ContainerAllocator> > {
  static const char* value() 
  {
    return "owd_msgs/ForceRead";
  }

  static const char* value(const  ::owd_msgs::ForceRead_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::owd_msgs::ForceRead_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64[] force\n\
\n\
";
  }

  static const char* value(const  ::owd_msgs::ForceRead_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::owd_msgs::ForceRead_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.force);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ForceRead_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::owd_msgs::ForceRead_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::owd_msgs::ForceRead_<ContainerAllocator> & v) 
  {
    s << indent << "force[]" << std::endl;
    for (size_t i = 0; i < v.force.size(); ++i)
    {
      s << indent << "  force[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.force[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // OWD_MSGS_MESSAGE_FORCEREAD_H

