controller_list:
#  - name: /barrett_hand/barrett_hand_trajectory_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#       - finger_1_med_joint
#       - finger_2_med_joint
#       - finger_3_med_joint
#       - finger_1_prox_joint
#       - finger_2_prox_joint
 - name: /barrett_hand/finger_1_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - finger_1_med_joint
      - finger_1_prox_joint
 - name: /barrett_hand/finger_2_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - finger_2_med_joint
      - finger_2_prox_joint
 - name: /barrett_hand/finger_3_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - finger_3_med_joint