controller_list:
  - name: fake_barrett_hand_controller
    joints:
      - finger_1_prox_joint
      - finger_1_med_joint
      - finger_2_prox_joint
      - finger_2_med_joint
      - finger_3_med_joint