(cl:in-package owd_msgs-srv)
(cl:export '(FORCE_X-VAL
          FORCE_X
          FORCE_Y-VAL
          FORCE_Y
          FORCE_Z-VAL
          FORCE_Z
          TORQUE_X-VAL
          TORQUE_X
          TORQUE_Y-VAL
          TORQUE_Y
          TORQUE_Z-VAL
          TORQUE_Z
          VIBRATE_HAND_X-VAL
          VIBRATE_HAND_X
          VIBRATE_HAND_Y-VAL
          VIBRATE_HAND_Y
          VIBRATE_HAND_Z-VAL
          VIBRATE_HAND_Z
          VIBRATE_AMPLITUDE_M-VAL
          VIBRATE_AMPLITUDE_M
          VIBRATE_FREQUENCY_HZ-VAL
          VIBRATE_FREQUENCY_HZ
          ROTATIONAL_COMPLIANCE-VAL
          ROTATIONAL_COMPLIANCE
          OK-VAL
          OK
          REASON-VAL
          REASON
          ID-VAL
          ID
))