(cl:in-package owd_msgs-srv)
(cl:export '(ENDPOINT_CHANGE-VAL
          ENDPOINT_CHANGE
          STARTING_CONFIG-VAL
          STARTING_CONFIG
          ENDING_CONFIG-VAL
          ENDING_CONFIG
          WRENCH-VAL
          WRENCH
          APPLYFORCE-VAL
          APPLYFORCE
          AF_X-VAL
          AF_X
          AF_Y-VAL
          AF_Y
          AF_Z-VAL
          AF_Z
          AF_F-VAL
          AF_F
          AF_ROTATIONAL_COMPLIANCE-VAL
          AF_ROTATIONAL_COMPLIANCE
          VIBRATE-VAL
          VIBRATE
          VIBRATE_HAND_X-VAL
          VIBRATE_HAND_X
          VIBRATE_HAND_Y-VAL
          VIBRATE_HAND_Y
          VIBRATE_HAND_Z-VAL
          VIBRATE_HAND_Z
          VIBRATE_AMPLITUDE_M-VAL
          VIBRATE_AMPLITUDE_M
          VIBRATE_FREQUENCY_HZ-VAL
          VIBRATE_FREQUENCY_HZ
          MAX_LINEAR_VELOCITY-VAL
          MAX_LINEAR_VELOCITY
          MAX_ANGULAR_VELOCITY-VAL
          MAX_ANGULAR_VELOCITY
          MIN_ACCEL_TIME-VAL
          MIN_ACCEL_TIME
          OPTIONS-VAL
          OPTIONS
          ID-VAL
          ID
          OK-VAL
          OK
          REASON-VAL
          REASON
))